python face.py --train_data=train.csv --test_data=test.csv --part=0 --train
python face.py --train_data=train.csv --test_data=test.csv --part=1 --train
python face.py --train_data=train.csv --test_data=test.csv --part=2 --train
python face.py --train_data=train.csv --test_data=test.csv --part=3 --train
python face.py --train_data=train.csv --test_data=test.csv --part=4 --train
python face.py --train_data=train.csv --test_data=test.csv --part=5 --train
python face.py --train_data=train.csv --test_data=test.csv --part=6 --train
python face.py --train_data=train.csv --test_data=test.csv --part=7 --train
python face.py --train_data=train.csv --test_data=test.csv --part=8 --train
python face.py --train_data=train.csv --test_data=test.csv --part=9 --train
python face.py --train_data=train.csv --test_data=test.csv --part=10 --train
python face.py --train_data=train.csv --test_data=test.csv --part=11 --train
python face.py --train_data=train.csv --test_data=test.csv --part=12 --train
python face.py --train_data=train.csv --test_data=test.csv --part=13 --train
python face.py --train_data=train.csv --test_data=test.csv --part=14 --train
python face.py --train_data=train.csv --test_data=test.csv --part=15 --train
python face.py --train_data=train.csv --test_data=test.csv --part=16 --train
python face.py --train_data=train.csv --test_data=test.csv --part=17 --train
python face.py --train_data=train.csv --test_data=test.csv --part=18 --train
python face.py --train_data=train.csv --test_data=test.csv --part=0 --test
python face.py --train_data=train.csv --test_data=test.csv --part=1 --test
python face.py --train_data=train.csv --test_data=test.csv --part=2 --test
python face.py --train_data=train.csv --test_data=test.csv --part=3 --test
python face.py --train_data=train.csv --test_data=test.csv --part=4 --test
python face.py --train_data=train.csv --test_data=test.csv --part=5 --test
python face.py --train_data=train.csv --test_data=test.csv --part=6 --test
python face.py --train_data=train.csv --test_data=test.csv --part=7 --test
python face.py --train_data=train.csv --test_data=test.csv --part=8 --test
python face.py --train_data=train.csv --test_data=test.csv --part=9 --test
python face.py --train_data=train.csv --test_data=test.csv --part=10 --test
python face.py --train_data=train.csv --test_data=test.csv --part=11 --test
python face.py --train_data=train.csv --test_data=test.csv --part=12 --test
python face.py --train_data=train.csv --test_data=test.csv --part=13 --test
python face.py --train_data=train.csv --test_data=test.csv --part=14 --test
python face.py --train_data=train.csv --test_data=test.csv --part=15 --test
python face.py --train_data=train.csv --test_data=test.csv --part=16 --test
python face.py --train_data=train.csv --test_data=test.csv --part=17 --test
python face.py --train_data=train.csv --test_data=test.csv --part=18 --test
